Zircon/Zircon.App/Areas/Admin/Controllers/ProductsController.cs
namespace Zircon.App.Areas.Admin.Controllers
{
    using Helpers.Messages;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Localization;
    using System.Threading.Tasks;
    using Zircon.Common.Constrants;
    using Zircon.Common.Admin.BindingModels;
    using Zircon.Services.Admin.Interfaces;

    public class ProductsController : AdminController
    {
        private readonly IAdminProductsService adminProductsService;
        private readonly IStringLocalizer<ProductsController> localizer;

        public ProductsController(IAdminProductsService adminProductsService,
            IStringLocalizer<ProductsController> localizer)
        {
            this.localizer = localizer;
            this.adminProductsService = adminProductsService;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = await adminProductsService.GetProductAsync();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddAndEditProductBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                this.TempData["__MessageType"] = MessageType.Warning;
                this.TempData["__MessageText"] = this.localizer[ErrorConstants.InvalidFormData];
                return View(model);
            }

            var id = await this.adminProductsService.AddProductAsync(model);

            this.TempData["__MessageType"] = MessageType.Success;
            this.TempData["__MessageText"] = this.localizer[SuccessConstants.ProductAdded].ToString();
            return this.RedirectToPage("/Products/Details", new { id });
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCategory(AddCategoryBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                this.TempData["__MessageType"] = MessageType.Warning;
                this.TempData["__MessageText"] = this.localizer[ErrorConstants.NoCategoryName];
                return View();
            }

            await this.adminProductsService.AddCategoryAsync(model);

            this.TempData["__MessageType"] = MessageType.Success;
            this.TempData["__MessageText"] = string.Format(this.localizer[SuccessConstants.CategoryAdded], model.Name);
            return RedirectToAction("Add");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.adminProductsService.GetEditProductDetailsAsync(id);
            return this.View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AddAndEditProductBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                this.TempData["__MessageType"] = MessageType.Warning;
                this.TempData["__MessageText"] = this.localizer[ErrorConstants.InvalidFormData];
                return View(model);
            }

            var id = await this.adminProductsService.EditProductAsync(model);

            this.TempData["__MessageType"] = MessageType.Success;
            this.TempData["__MessageText"] = this.localizer[SuccessConstants.ProductEdited].ToString();

            return this.RedirectToPage("/Products/Details", new { id });
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await this.adminProductsService.DeleteProductAsync(id);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Zircon/Zircon.App/Areas/Admin/Controllers/UsersController.cs
namespace Zircon.App.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using Zircon.Models;
    using Zircon.Services.Admin.Interfaces;

    public class UsersController : AdminController
    {
        private readonly UserManager<User> userManager;
        private readonly IAdminUsersService adminUsersService;
        public UsersController(
          IAdminUsersService adminUsersService,
            UserManager<User> userManager)
        {
            this.adminUsersService = adminUsersService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await userManager.GetUserAsync(this.User);
            var users = await this.adminUsersService.GetUsersAsync(currentUser.Id);

            return View(users);
        }
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var model = await this.adminUsersService.GetUserDetailsAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
    }
}

Zircon/Zircon.App/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer LayoutLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @this.LayoutLocalizer["Zircon (Admin)"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="navbar-brand"> @LayoutLocalizer["Zircon (Admin)"]</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">@LayoutLocalizer["Home"]</a></li>
                <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">@LayoutLocalizer["About"]</a></li>
                <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Contact" class="nav-link">@LayoutLocalizer["Contact"]</a></li>
                <li class="nav-item"><a asp-area="Admin" asp-controller="Users" asp-action="Index" class="nav-link">@LayoutLocalizer["All Users"]</a></li>
                <li class="nav-item"><a asp-area="Admin" asp-controller="Products" asp-action="Add" class="nav-link">@LayoutLocalizer["Add Product"]</a></li>
                <li class="nav-item"><a asp-area="Admin" asp-controller="Products" asp-action="AddCategory" class="nav-link">@LayoutLocalizer["Add Category"]</a></li>
                <li class="nav-item"><a asp-area="Admin" asp-page="/GiftCards/Add" class="nav-link">@LayoutLocalizer["Add Gift Card"]</a></li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @if (TempData.ContainsKey("__MessageType"))
        {
            Enum.TryParse(@TempData["__MessageType"].ToString(), out MessageType type);
            <message type=@type message="@TempData["__MessageText"]"></message>
        }
        @RenderBody()
        <hr />
        <footer>
            <partial name="_SelectLanguage" />
            <p>&copy; 2018 - Zircon</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>